/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hongfans_ndkdemo_JNIUtil */

#ifndef _Included_com_hongfans_ndkdemo_JNIUtil
#define _Included_com_hongfans_ndkdemo_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hongfans_ndkdemo_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hongfans_ndkdemo_JNIUtil_getWorld
        (JNIEnv *, jobject);

/*
 * Class:     com_hongfans_ndkdemo_JNIUtil
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hongfans_ndkdemo_JNIUtil_getHello
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
